### ISSUE TITLE
Docs: New logo

### ISSUE THREAD

**Issue by jtommy** [oruga-ui/oruga-bulma#8]
Using Oruga logo and Bulma logo "draw" a new logo to publish in the Readme and in the official docs.

Your profile will be mentioned in the README 🎉

**Comment by chamindujs** [comment]
![bulLogo](https://user-images.githubusercontent.com/41909955/135511218-3825a9b8-e8a6-40db-b24b-f12bfb6e8e1a.png)
How about this logo?

**Comment by jtommy** [comment]
@chamindujs Mmm, no 😐

**Comment by chamindujs** [comment]
@jtommy Do you want them to be separated?

**Comment by jtommy** [comment]
@chamindujs your base idea is not bad because Bulma "wears" Oruga but probably it's too mixed.
You might try something similar or given that the final stage of Oruga (caterpillar) is a butterfly you might design a butterfly with Bulma logo and colors, what do you think ? 😉

**Comment by astagi** [comment]
![base](https://user-images.githubusercontent.com/537363/135627393-c6cc8a40-e447-4802-9eb0-60f0a88f780b.png)

I agree with @jtommy also Bulma logo could be used as wings 🦋 Anyway thank you for your interest and effort @chamindujs do you think it's possible for you to make something related to butterflies?

**Comment by chamindujs** [comment]
On it!

**Comment by chamindujs** [comment]
![image](https://user-images.githubusercontent.com/41909955/135648442-eef8d698-f304-4aee-87f0-3866273483e0.png)


How about this one guys?

**Comment by jtommy** [comment]
@chamindujs it's no mandatory to use Oruga logo, you can use part of it or don't use it but the final result should be a butterfly with Bulma logo/colors.

**Comment by astagi** [comment]
@chamindujs I really love wings! yes Oruga logo is not mandatory, anyway it would be great to unroll it and use as body (I've shared a sketch below). I suggest to use the main Bulma color for wings and body, and use svgs ([Oruga logo svg](https://raw.githubusercontent.com/oruga-ui/oruga/develop/packages/docs/.vuepress/public/oruga.svg) and Bulma svg logo [bulma-vector-logo-78C6997676-seeklogo.com.zip](https://github.com/oruga-ui/oruga-bulma/files/7271330/bulma-vector-logo-78C6997676-seeklogo.com.zip)) as source. What about?

![photo1633172597](https://user-images.githubusercontent.com/537363/135713454-aa43a12e-6175-481e-9891-4f950619f471.jpeg)

**Comment by astagi** [comment]
@rubjo we've chosen the third logo as the official one! Just a little improvement if possible: we'd like to have the left wing equal to the right one, mirrored. Feel free to open a new PR and remove the other logos.
